# Use this prefix to filter out specific files. Set to "" to disable
PREFIX: "V2Rpp"

# Set names of your samples. A folder will be created for each of them. You can have either one or four
SAMPLES:
  - C-tail 1
  - FL
  - Cdom
  - C-tail 2

# Whether you want to run autotrace on each individual rawtraces file
AUTOTRACE_EACH: true

# Plotting - what plots to save?
PLOTS:
  extract_samples: true
  contour_individual: true
  contour_combined: true
  contour_N_frames: 500
  contour_formats:
#    - fig
    - png
#    - pdf
